import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Footer from "../app/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const body = {
    overflow: "hidden",
  } as const;

  const footer = {
    position: "sticky",
    top: "100vh",
    width: "100%",
  } as const;

  return (
    <html lang="ja">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossOrigin="anonymous" />
      </head>
      <body className={inter.className} style={body}>
        <Suspense>
          {children}
        </Suspense>
        <div style={footer}>
          <Footer />
        </div>
      </body>
    </html>
  );
}
